---
- name: Playbook to configure ansible controller post installation
  hosts: localhost
  connection: local
  pre_tasks:
    - name: Include vars from controller_configs directory
      ansible.builtin.include_vars:
        dir: ./yaml
        ignore_files: [controller_config.yml.template]
        extensions: ["yml"]
  roles:
    - {role: infra.controller_configuration.job_templates, when: controller_templates is defined}
